# Name of the Flex file
FLEX_FILE = simple.l

# Output generated by Flex
LEX_OUTPUT = lex.yy.c

# Compiler and flags
CC = gcc
CFLAGS = -Wall

# Target for building the scanner
all: scanner

# Rule to generate the scanner source file using Flex
$(LEX_OUTPUT): $(FLEX_FILE)
	flex -d -Cf -b --reentrant $(FLEX_FILE)

# Rule to compile the scanner
scanner: $(LEX_OUTPUT)
	$(CC) $(CFLAGS) -o scanner $(LEX_OUTPUT) -lfl

# Clean up generated files
clean:
	rm -f $(LEX_OUTPUT) scanner

.PHONY: clean

